before:
  hooks:
    - go mod download
builds:
- main: ./cmd/protod
  binary: protod
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^ci:'
    - '^docs:'
    - '^test:'
